### ISSUE TITLE
Support Android Studio out of the box

### ISSUE THREAD

**Issue by nbeni** [manifoldjs/ManifoldJS#10]
In order to support Android Studio out of the box, you need to add the CordobaLibs project into the sourceSets section of the build.gradle

sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src', 'CordobaLib/src']
            resources.srcDirs = ['src', 'CordobaLib/src']
            aidl.srcDirs = ['src', 'CordobaLib/src']
            renderscript.srcDirs = ['src', 'CordobaLib/src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
    }

This should be added as a post script of the tool

**Comment by nbellocam** [comment]
This is now supported by [cordova-android](https://github.com/apache/cordova-android) out of the box: 

* https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md
* http://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html

The problem is that CordovaLib is still targeting the older version. 

However, we can target to the newest version using the following commands as its described on the announcement.
```
cordova-android@4.0.0 will be the default android version in the next version of cordova. If you just can’t wait though, you can try it out now:

cd my_project
cordova platform update android@4.0.0
cordova plugin add https://github.com/apache/cordova-plugin-whitelist.git#r1.0.0
```

**Comment by nbellocam** [comment]
A temporary workaround was applied until we migrate to the latest version of cordova-android: https://github.com/manifoldjs/ManifoldJS/commit/b18d2925d00f5abac2bcf051f6bf21d378ea02fa
