### ISSUE TITLE
Building Manifold project on iOS fails to produce files in "platforms" folder

### ISSUE THREAD

**Issue by DaveVoyles** [manifoldjs/ManifoldJS#101]
**Steps to reproduce:**
1. Attempt to build ManifoldJS project on OS X, either via CLI or web interface
2. Site used: famous-angular-pokemon.azurewebsites.net/app and using *-l debug* param
3. Open Manifold folder

**Expected Result:**
Platforms folder will have iOS and Android projects 

**Actual Result:**
Platforms folder is empty 

![](https://dl.dropboxusercontent.com/s/il84jgy9k3z7hwh/Screenshot%202015-06-26%2008.41.23.png?dl=0)

When building from the web interface on OS X, here is what happens:
![](https://dl.dropboxusercontent.com/s/lq1k5wxpat0pngq/Screenshot%202015-06-25%2016.39.39.png?dl=0)

**Comment by f2bo** [comment]
This is caused by an issue in the current release for Cordova when adding the Windows platform and can be reproduced in both MacOS and Linux.

It can be reproduced without ManifoldJS by executing the following Cordova commands:
``` 
 cordova create newApp
 cd newApp
 cordova platform add windows
``` 
I'm afraid the only workaround until they fix the problem in Cordova is to exclude the Windows platform when building projects in Linux or MacOS by using the **-p | --platforms** command line parameter. For example,
``` 
manifoldjs http://your.site/ .... -p ios,android,firefox,chrome,web
``` 
Regarding the error experienced using the web interface, this is caused by an unrelated issue that prevents the generation of projects for the iOS platform. We are currently investigating the cause and expect to have a resolution soon but for the time being you should be able to use the web interface to generate projects for all platforms except iOS.

**Comment by DaveVoyles** [comment]
Thanks for clarifying! Good to know that the team was aware of it. I was scratching my head trying to figure it out. 

I can exclude the Windows build for now. 

For the time being I'll just use the CLI. I've been putting together a tutorial on this, so I'll make note of this now.
