### ISSUE TITLE
The connection to the server was unsuccessful

### ISSUE THREAD

**Issue by cometta** [manifoldjs/ManifoldJS#104]
When I installed the apk into android phone and ran on the first time, i get error The connection to the server was unsuccessful (https://.... )  . I have then pressed OK and got into my home screen and press my application icon to launch the app, the app is able to run.   I repeatedly tried this few times, and consistently able to get similar error. Anyone else is facing similar issue?

**Comment by msrodri** [comment]
Seeing similar issues in a mobile phone with an internet data plan and when there is poor cellular signal in the device, or no signal at all. We'll check into this in more detail.

**Comment by boyofgreen** [comment]
I think we have a similar issue where we don't hit the offline page if the app launches offline.  Maybe this is the same

**Comment by mildmojo** [comment]
Looking for this error with cordova apps, I turned up a few [StackOverflow questions](http://stackoverflow.com/questions/23514622/cordova-connection-to-server-was-unsuccessful) that say it happens when the first page load times out (as with large pages or slow net connections).

A hack workaround (as noted on that SO question) is to have the app's first page be a stub that fully loads but immediately sets `window.location` to the real page. I'm new to Cordova and ManifoldJS so I don't know where to make that change. The project seems to load the hosted app URL directly as listed in `config.xml` rather than using anything in the project's `www` dir.
