### ISSUE TITLE
support wildcard for mjs_access_whitelist

### ISSUE THREAD

**Issue by cometta** [manifoldjs/ManifoldJS#105]
I have tested that mjs_access_whitelist does not support wildcard like "https://*.google.com"  , this is very inconvenient . Can help to support this?

**Comment by cometta** [comment]
so that we do not need to define for each subdomain.google.com

**Comment by kenchris** [comment]
It seems a bit dangerous though and people can add a new subdomain and you have no control over that

**Comment by cometta** [comment]
Reason being that i tried white list accounts.google.com  and still external browser pop up in order to authenticate through google.  Nevertheless, *.google.com are consider safe

**Comment by boyofgreen** [comment]
Fernando will probably know the best, but our whitelist rules are based on what the different platforms allow.  iOS, Android and Windows 10 all have whitelist requirements.  I'll assign this to Fernando to see if he can clarify that wildcard hosts are allowed or not.

**Comment by f2bo** [comment]
Let me give you a (quick?) answer here for the time being, but we'll prepare a more polished wiki article with guidance on this topic.

The mjs_access_whitelist **does** support wildcards. I'll illustrate with an example.

**Note:** This describes how to troubleshoot the whitelist for an Android app using the Chrome DevTools. The details will be different for other platforms, but the basic idea is the same.

- Run ManifoldJS against the following site: 
  ```
  manifoldjs http://shiftr.azurewebsites.net
  ```

- Build the app and deploy it to a device or the emulator

- Open **Chrome** in your desktop and navigate to _chrome://inspect_

- In the **Devices** tab, you should see the device (or the emulator) listed in the right pane and nested below it, two WebViews

- Open the Developer Tools by selecting **inspect** for the WebView where the site's content is loaded (http://shiftr.azurewebsites.net) 

- Switch to the **Network** tab and use the app (by clicking the X or heart buttons) while monitoring the network requests it makes

- Verify that all (or most) networks requests succeed

- When you reach the ASP.net page (the order is random), click **home page** (notice that the page is launched in the browser instead of the app because the URL is not whitelisted)

- Open **manifest.json** in [yourapp-folder]/cordova and add the last entry to the **mjs_access_whitelist** (the first three entries should already be there)
  ``` JSON
    "mjs_access_whitelist": [
        {
            "url": "https://avatars1.githubusercontent.com/u/6476660"
        },
        {
            "url": "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"
        },
        {
            "url": "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/fonts/glyphicons-halflings-regular.woff"
        },
        {
            "url": "https://github.com/aspnet"
        }
    ]
  ``` 

- Prepare and build the Cordova project again to apply the new access rules

- Deploy the updated package to the device or emulator and repeat the previous steps to capture network requests (you'll need to open a new Developer Tools window as the previous one became detached)

- Go to the home page for ASP.net again and notice that even though it now opens inside the app, it doesn't render correctly because some of the CSS and script files are being blocked

- Look in the network capture to see which requests failed

- Update **manifest.json** to add the last two entries to the whitelist (presumably you should see the same URLs in the requests that failed)

  ``` JSON
    "mjs_access_whitelist": [
        {
            "url": "https://avatars1.githubusercontent.com/u/6476660"
        },
        {
            "url": "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"
        },
        {
            "url": "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/fonts/glyphicons-halflings-regular.woff"
        },
        {
            "url": "https://github.com/aspnet"
        },
        {
            "url": "https://assets-cdn.github.com/assets/mobile/index-c0bd7f7bc32e9f8f6944b1eaa52e662dfa5546225b1e0e3680e9739bb4985446.css"
        },
        {
            "url": "https://assets-cdn.github.com/assets/mobile/index-fa99c2f2c7f0199975a6038a45f19fa21f8e44bb1cf433adf858563de5b85b33.js"
        }
    ]
  ```

- Prepare and build the Cordova project again

- Deploy the updated package and test the ASP.net home page again--notice that it renders correctly

- You will also see that now that the app loads the CSS and script files that were previously blocked, there are additional requests that fail (this is an iterative process and it will be different for every app)

Now, to answer your question **"Does mjs_access_whitelist support wildcards?"**

- Update **manifest.json** again and replace the last two entries with a single entry **that uses wildcards** as shown below.

  ``` JSON
    "mjs_access_whitelist": [
        {
            "url": "https://avatars1.githubusercontent.com/u/6476660"
        },
        {
            "url": "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"
        },
        {
            "url": "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/fonts/glyphicons-halflings-regular.woff"
        },
        {
            "url": "https://github.com/aspnet"
        },
        {
            "url": "https://*.github.com/assets/mobile/*"
        }
    ]
  ```

- Test the app again and verify that it can still load the CSS and script files successfully

**Note:** In the Windows 10 platform, earlier builds did not support wildcards for hosted web apps. We tested this in yesterday's release (sorry, I don't have the build number right now) and it works as expected. Also, the whitelist applies only to navigation--network requests are always allowed.

**Comment by cometta** [comment]
Hello @f2bo ,  Thank you for the intrinsic explanation . I think the current white list unable to support http://*.github.com/*   and hence required to enter all combinations of paths  "https://*.github.com/assets/mobile/*"  , "https://*.github.com/assets/tv/*"   to access different sub-tree ?

**Comment by f2bo** [comment]
I'm not sure if the dot prefix when you write _"http://**.**github.com/..."_ is intentional or a typo. In any case, you should use _"http://github<span></span>.com/..."_ in you whitelist. 

If you want to grant access to the **entire** _assets_ subtree, you can use something like the following in your whitelist.

``` 
  "mjs_access_whitelist": [
      ...
      {
          "url": "https://github.com/assets/*"
      }
  ]
``` 

However, it's always a good idea to be as specific as possible and only whitelist URLs that you know are safe.

If this is not working for you, make sure that you are using the latest release of ManifoldJS, which targets Cordova 5.1.1.

**Comment by cometta** [comment]
Let me share my observation with my testing. At the moment, the website is able to display in webview without need to use external browser in emulator-nexus 5 . However, when I tried it on real android phone, on the page where Google shows 'sign in with your google account, after I have keyed in password and pressed 'sign in' , It prompt for external browser. I already tried many rounds and have similar outcome. I have tried with _debug.apk as well as _release.apk+signed.

**Comment by f2bo** [comment]
Could it be that the emulator and the device have different user agent strings and the site responds with different content for each one?  I recommend that you follow the troubleshooting steps using the Chrome DevTools I described in my previous reply to see if any URLs that you haven't whitelisted are being blocked. You can use this technique with the device and the emulator.

**Comment by boyofgreen** [comment]
Hi Coetta, I'm closing for now, let me know if you run into more issue, we'll look with you.  White list can be hard because you have to be able to catch all the different domains and auth can be tricky with that.

**Comment by cometta** [comment]
Hi team,
 Sorry for late reply. I am finally able to share a conclusion after I did few round of testing.  
  1. I have tested this is lower version of android 4.22 and disappointed to say that webview will prompt for external browser if version is less than kitkat. I have tested this in real phone as well as emulator

  2. The chrome debug tool that you shared only work for kitkat and above,therefore i cannot check the network request for 4.22 in emulator or real phone
  
Do let me know if this ticket needs to be reopen as this evidence conspicuously showed that  Manifoldjs will not work for version of android lower than kitkat.

**Comment by f2bo** [comment]
1. When you say "_webview will still prompt for an external browser if the version is less than kitkat_", are you saying that you've tested the same site with more recent Android versions and you don't see the problem?  If so, did you try enabling Crosswalk when generating the app with ManifoldJS? (see the **-c** | **--crosswalk** command line parameter) When you do this, it will use a different webview that is based on Chromium regardless of the Android version installed in the device. 

2. This may be the case, but unless you have reason to believe that the site is returning different content depending on the Android version, you may still be able to use this technique with an Android 4.4+ emulator to determine which URLs are being hit. Otherwise, you may need to see blocked requests from the app using some other means. For example, try reading the Android console log with adb logcat.

**Comment by cometta** [comment]
1. I have followed your advice by added --crosswalk on android emulator 4.22 . However, it still prompts for external browser. Yes, this does not happen in KitKat, only for lower version of android

2. I have got this from adb logcat when it opens external browser  (I have censored some content)

I/ActivityManager( 1211): START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://accounts.google.com.my/accounts/SetSID?ssdc=1&sidt=CENSORED_CONTENT+CENSORED_CONTENT/CENSORED_CONTENT+CENSORED_CONTENT+CENSORED_CONTENT&continue=https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/plus.login+https://www.googleapis.com/auth/userinfo.email+https://gdata.youtube.com&response_type=code&access_type=offline&redirect_uri=https://www.mywebsite.com/auth/google&client_id=CENSORED_CONTENT.apps.googleusercontent.com&request_visible_actions=https://schemas.google.com/CreateActivity+https://schemas.google.com/CommentActivity&hl=en-GB&from_login=1&as=CENSORED_CONTENTb&dbus=TW.2 cmp=com.android.browser/.BrowserActivity} from pid 2141

D/dalvikvm( 1211): GC_FOR_ALLOC freed 1060K, 18% free 7363K/8936K, paused 9ms, total 11ms
W/InputMethodManagerService( 1211): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@b52ef628 (uid=10033 pid=2079)
W/InputMethodManagerService( 1211): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@b52ef628 (uid=10033 pid=2079)
D/WebViewTimersControl( 2079): onBrowserActivityResume
D/WebViewTimersControl( 2079): Resuming webview timers, view=com.android.browser.BrowserWebView{b50f8ed8 VFEDHVCL .F....I. 0,0-0,0}
D/dalvikvm( 2079): GC_CONCURRENT freed 536K, 12% free 5187K/5860K, paused 0ms+1ms, total 7ms
W/InputMethodManagerService( 1211): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@b52ef628 (uid=10033 pid=2079)
W/InputMethodManagerService( 1211): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@b52ef628 (uid=10033 pid=2079)
E/SurfaceFlinger(  794): ro.sf.lcd_density must be defined as a build property
W/EGL_emulation( 2079): eglSurfaceAttrib not implemented
W

**Comment by f2bo** [comment]
Hi @cometta,

I think you misunderstood me. You need to generate the application again with ManifoldJS to enable Crosswalk, this time specifying the (-c | --crosswalk) command line parameter. For example,

``` Javascript
manifoldjs http://your.site.com -c ...
```
Sorry I wasn't clear. I don't know what `cordova emulate --crosswalk` does.

**Comment by cometta** [comment]
a good news for everyone. It's working like a magic ! thank you so much. I am able to run in on lower version of android.

**Comment by f2bo** [comment]
Good to hear! 

Just to be sure, the solution that worked was to use ManifoldJS to generate the application again with Crosswalk enabled?

**Comment by cometta** [comment]
exactly.
