### ISSUE TITLE
Icon submission looks scary.

### ISSUE THREAD

**Issue by Gr8Gatsby** [manifoldjs/ManifoldJS#111]
For the Icon submission there are a whole lot of images and red 'X's showing, this feels like a lot of work, can we add a simple image generator that produces all the different sizes. Let folks worry about adding all the specific brand images later.

**Comment by f2bo** [comment]
Just to be clear, you are referring to the manifoldjs.com site, correct?

The list of icons shown by the site once you provide a site URL or a manifest correspond to the icons that are already defined in the manifest and the red 'X's are simply there to allow you to remove them, in case you prefer not to include one or more of them in the generated package. 

So these are the icons that you **don't** need to worry about because, presumably, if they are defined by the site's manifest and have a valid URL, the images should already exist and ManifoldJS should be capable of downloading them from their current location and embedding them in the app. 

What you might want is to pay attention to the right pane that shows the manifest. It also lists any missing icons that are used in each of the supported platforms. The items in this list are usually recommendations and will not prevent you from generating an application. Any images that are not provided will be substituted by a ManifoldJS icon of the same size. You can always replace this icon with another one later on.

Regarding the image generator, this is a good idea and it's already in our plans.

By the way, there's currently an issue in the site where the icon preview fails if both the start_url and icon src members are relative URLs. We are currently tracking this as a [Github issue] (https://github.com/manifoldjs/manifoldjs-site/issues/159).

**Comment by martinkearn** [comment]
Not an answer but you can find an image generator that creates images for ManifoldJS here: http://appimagegenerator.azurewebsites.net/

It is still work in progress and it open on GitHub so if you want to send pull requests, please do: https://github.com/martinkearn/App-Image-Generator

There may be plans to bring this into the ManifoldJS tool set, but at this time it is still separate.
