### ISSUE TITLE
change behavior of 'back' button on mobile devices

### ISSUE THREAD

**Issue by cometta** [manifoldjs/ManifoldJS#123]
At the moment, when a user pressed 'back' button on the mobile devices , webiew will display previous page that user had visited. In my opinion, this is not right. For instance, a user that just wanted to quit the webview but instead has been showing all previous pages of google ouath authentication which use to login into application. Can we have a option when generating manifoldjs which change this behavior?

**Comment by boyofgreen** [comment]
Hi Cometta,
  We have a toolkit we will be releasing soon that provides some back button functionality among other things.  This will be another plugin we add to the cordova project.  We're trying to keep this out of the main manifoldjs functionality because we want to keep that focused on packaging.  Look for it to come out around the end of next week.
Thanks,
Jeff

**Comment by cometta** [comment]
Hi @boyofgreen , can elaborate more on the toolkit that you mentioned? What is the url to download it? What extra steps that I need to do to use with manifoldjs

**Comment by cometta** [comment]
@boyofgreen , may I know where can I get the plugin that you mentioned?
