### ISSUE TITLE
don't require a short name

### ISSUE THREAD

**Issue by boyofgreen** [manifoldjs/ManifoldJS#145]
We should not require a short name.  If they don't have one, but have a name value, we should use that.  If none is present, do what we do when there is no manifest and make it from url.

Exmaple site:
https://www.npmjs.com/static/images/touch-icons/manifest.json

**Comment by fcatae** [comment]
Investigation:

A default name is created in getManifestFromSite().

      var shortName = '';
      url.parse(siteUrl)
         .hostname
         .split('.')
         .map(function (segment) {
                segment.split('-')
                       .map(function (fraction) {
                              shortName = shortName + utils.capitalize(fraction);
                        });
          });

getW3cManifest() function retrieves the app manifest. once it gets the
result back, then we can implement a default value for short_name. 

According to the w3c spec, there is no constraint for short_name
http://www.w3.org/2008/webapps/manifest/#short_name-member

**Comment by fcatae** [comment]
In order to maintain compatibility, I will encapsulate the name into a specific function
for later reuse.

I will NOT set the short_name inside getW3cManifest() because the spec allows returning
an undefined value.

The implementation will happen inside the main program execution, and I set the short_name
value as follow:

      short_name = short_name || name || createFromUrl()
