### ISSUE TITLE
Whitelist is not working

### ISSUE THREAD

**Issue by dmitrymal** [manifoldjs/ManifoldJS#194]
I realize this may not be an issue with the manifoldjs or cordova. Most likely, it is me doing something wrong, but I can't seem to find a solution to this. Here is the issue I am running into:

I generated an iOS hosted app for the site (http://www.twincitieschessclub.com/). It works (at least when I debug it with Xcode 7), but unfortunately, all external links jump out of the hosted app and get opened in the browser. I also have some google ads running on the site. Those ads would not stay in the hosted app either, but rather get opened up in the browser. This really looks bad. I followed the cordova-plugin-whitelist documentation and I think I opened pretty much everything I could:
```xml
<!-- A wildcard can be used to whitelist the entire network,
     over HTTP and HTTPS.
     *NOT RECOMMENDED* -->
<allow-navigation href="*" />

<!-- Allow all unrecognized URLs to open installed apps
     *NOT RECOMMENDED* -->
<allow-intent href="*" />

<!-- Don't block any requests -->
<access origin="*" />
```
I'd appreciate any suggestions on how to troubleshoot this.  

Thanks!

**Comment by dmitrymal** [comment]
A quick update.
After using Cordova natively and running the following commands manually everything worked as a charm:

1. Install Cordova: sudo npm install -g cordova
2. Installed GitHub desktop client (not sure if this is required)
3. Created a test project: $ cordova create hello com.example.hello HelloWorld
4. Added iOS platform to the project: $ cordova platform add ios
5. Opened up the project in Xcode
6. Changed <content src="index.html" /> to <content src="http://www.twincitieschessclub.com/" />

Works with no problems.

Any ideas why this is not working with manifoldjs? I spent days trying to make it work (with manifoldjs). I never used Cordova before and thought manifoldjs is here to help, so I wasn't even looking at using Cordova natively. It turns out Cordova is not that difficult. I spent literally less than 1 hour with Cordova following their instructions and it worked. 

What am I missing? (I wish manifoldjs could've done better) :disappointed:

**Comment by boyofgreen** [comment]
Adding @f2bo as well, he knows the most about whitelist.  Generally we suggest controlling the scope with the manifest when using manifoldjs.  So you could wildcard your scope and that should allow everything in.  In tern this should have generated a whitelist entry like this:

```
<allow-navigation href="*" />
```
I'm not sure how whitelist will react if you add the wildcard on top of a different scope rule, that might be where it got tripped up.

I agree that Cordova isn't so hard, what we add on top of it is offline behavior, and adding the plugins to your code, which you will no longer get when you stop pointing to index.html.  Most of all, we want devs to focus on the W3C manifest, get it on their sites and start using it as the manifest or record.  As support for the standard grows, manifoldjs can fade away :)

**Comment by f2bo** [comment]
By default, manifoldjs, or more precisely the **cordova-plugin-hostedwebapp** plugin which is used to host web content, restricts navigation to URLs that belong to the scope defined by the W3C manifest. The scope includes the hosted site's URL as well as its children. In the latest release of manifoldjs, the scope can be extended by including a custom **mjs_extended_scope** element, which is an array of URLs that will also be opened inside the app. Anything outside the scope will be opened in the browser, as you've already seen. 

So, for example, to allow navigation to your _yoursite.com_ as well as to _otherdomain.com_ and _admin.yoursite.com/registration_, your manifest should include the following information:
```
{
   ...
   "start_url": "http://yoursite.com/",
    "scope": "/",
    "mjs_extended_scope": [
        "*://otherdomain.com/*",
        "https://admin.yoursite.com/registration/*"
    ],
    ...
}
```
You can update a copy of the manifest you already have for your site with information similar to the one above and then re-run manifoldjs using the updated manifest as input. To use it, instead of running
```
manifoldjs http://yoursite.com ...
```
 you can run
```
manifoldjs -m <path-to-updated-manifest.json-file> ...
```

**Comment by amitjainuk** [comment]
Same issue - works like a charm with Cordova - no proper documentation -  half baked solution - very much a hallmark of microsoft now-a-days - What a waste of my time on manifoldjs - Signing out of Manifoldjs!!!!
