### ISSUE TITLE
Idea: Support for caching HTML files to help w/ lag etc...

### ISSUE THREAD

**Issue by mattwoberts** [manifoldjs/ManifoldJS#196]
This is something I'm thinking about for the mobile app I'm building...

So - the idea of a a hosted app is great. But - when you load a mobile app that loads all of it's content from a remote server, you're going to get some lag... Especially when you're not on a wifi network, things start to get slower....

So - I was thinking - wouldn't it be cool if we could cache / store the content locally and serve it up from there, once loaded from the remote server.

We could use the cordova file API (https://github.com/apache/cordova-plugin-file) to get the content, store it locally, and then subsequent requests can be loaded up from the local store. We'd have to store all the assets that the page needs too...

I'm playing about with this idea to see if I can get something working with that plugin and some js, but if this was part of manifoldjs, I think that would be very cool indeed.

**Comment by ansorg** [comment]
isn't that what appcache or service worker are supposed to handle (in the hosted web site)?

**Comment by mattwoberts** [comment]
@ansorg app cache is now deprecated - it won't be supported in future browsers and cordova no longer supported

service workers - not sure. I don't know a massive about about the technology to be honest, I'm not sure if this could be used to serve up pages from a cache rather than from the remote URL...

**Comment by boyofgreen** [comment]
our play is to support the "progressive web app" strategy that we will see coming in each of the major browsers.  This starts with the W3C manifest, then moves into things like service workers.  @mattwoberts  we did try to build a similar system back in the "web app template" and found out it was super hard to do in a way that worked across different web apps. We decided to not try to solve that ourselves here, and instead push on the W3C to come up with a great solution (which I think they have).  We are just at a bad spot in time where AppCache is not a great solution, and serviceworkers just aren't out there yet.  Trust me, I can't wait to have a better answer for this one :)

**Comment by yasin-siddiqui** [comment]
@mattwoberts If this is a 'new' app that you're building, I'd suggest that you use the following together to achieve what you're looking for:
a. Crosswalk (manifoldjs --crosswalk) - so that you can use the Service Worker API & File API
b. UpUp library (https://www.talater.com/upup/) - to make Service Worker super-easy for you
c. imgcache.js (https://github.com/chrisben/imgcache.js/) -  to make image caching and retrieval easy
d. PouchDB (http://pouchdb.com/) - if your app needs to use/store data

I'm assuming most people use ManifoldJS to quickly convert an existing responsive website into an app, and these techniques wouldn't be very helpful for them because they need to be incorporated at the architecture level.

**Comment by mattwoberts** [comment]
@boyofgreen Great - I assumed that this was the case, and that future work with servive workers would probably be the solution here, thanks for the confirmation.

@yasin-siddiqui Cheers very much for the advice here :-) It is an existing web application that we're making more responsive and then using manifoldJS to turn into a web app, but it's the single biggest concerrn we have - the lag for loading pages. We're going to see what the end user feedback is first and then take it from there.
