### ISSUE TITLE
Cannot download images via console

### ISSUE THREAD

**Issue by martinkearn** [manifoldjs/ManifoldJS#197]
When using NPM to create ManifoldJS apps, I get a load of errors saying "WARNING: Failed to download icon file: http://pathtoimage".

When I run in debug, I see the attached which suggests that it is struggling to create the folder because it is based on the full url and presumably does not like use of '\' in the folder name.

The command i'm using is: manifoldjs http://sentimentalweb.azurewebsites.net -d C:\Manifold -l info -b'''

This is on Windows 10.
<img width="1079" alt="manifold image path issue" src="https://cloud.githubusercontent.com/assets/2410726/12166925/0d3d29ec-b521-11e5-8a15-f7c42ce5cdfd.PNG">

**Comment by boyofgreen** [comment]
Hi Martin,
  Looking at right now.  We're doing some overhauling, and it might be that we broke something

**Comment by boyofgreen** [comment]
Hi Martin,
  I'm seeing a few things when I run it locally.  

- WARNING: Failed to download icon file:  this one doesn't seem to be reporting correctly, as it is downloading the icons okay and applying them.

- Invalid download directory: this one is an accurate error, it's not moving the images into the chrome directory, so that is actually something broken

- I noticed you have some of the image values in there twice (like 48x84 for both FF and chrome).  This doesn't seem to be breaking anything that I can tell, but I don't think we actually took this scenario into account, so I'm not sure if it's using the first or the second one.

At any rate I'm going to break this into two different issues for us to work.
now issues #198 and #199 

are either of these blocking to you?

**Comment by martinkearn** [comment]
Thanks Jeff,
No, these are not blocking as such but I have a live demo planned for Friday 15th so it would be awesome if it was resolved for then. Having said that, I can easily work around by having a zip pre-created from the website which seems to work fine.
Cheers

**Comment by boyofgreen** [comment]
So I'm testing out on the new version which should be out next week.  Just in time for your conference.  Maybe you can be the first to announce the new version to the community for us?  Let's email

**Comment by boyofgreen** [comment]
closeing this issue, #198 and #199 replaceing it

**Comment by martinkearn** [comment]
I'm having this same issue again with a new site. 

The site is http://howhappy.co.uk

The manifest links to images using this url structure: http://howhappy.co.uk/images/windows-squarelogo-150-150.png and the URLs are known to resolve.

You can see the manifest here: http://howhappy.co.uk/manifest.webmanifest

When trying to generate app packages using NPM, I'm getting a 404 and validation warnings for all of the images and the packages contain the default manifoldjs logo. This happens for all platforms.

The command I'm using is `manifoldjs http://howhappy.co.uk/ -d c:\demodump\hh3`
![capture](https://cloud.githubusercontent.com/assets/2410726/14112582/2225d9f8-f5c7-11e5-9b4d-aa4a1fa59aa5.PNG)

I've tried a few different URL structures in the manifest but none of them work. You can see from eth MD output that the URL ManifoldJS is trying to get tehimages form is not the URL in the manifest and is not valid.

**Comment by boyofgreen** [comment]
Sorry Martin, can you share your NPM version and Node.js version?  I'll take a look

**Comment by f2bo** [comment]
Hi Martin,

The home page of the site appears to be linking to a different manifest than the one you mention and its images are not pointing to valid locations (404 Not Found). This is the manifest that is currently referenced in the HEAD element of the home page.
```
<link rel="manifest" href="/images/manifest.json">
```

However, I did test the manifest at http://howhappy.co.uk/manifest.webmanifest with manifoldjs. There were a couple of issues with the manifest that I had to correct before it would work.

- The **start_url** member needs to be a full url: _http://howhappy.co.uk_ rather than _howhappy.co.uk_
- The icons member is **sizes** rather than **size**.

Once I corrected these two issues all its images downloaded successfully.
