### ISSUE TITLE
Provide a URL or manifest: provide URL to manifest instead of uploading it

### ISSUE THREAD

**Issue by kenchris** [manifoldjs/ManifoldJS#28]
Sites like cnet.com already have a manifest.json (http://www.cnet.com/manifest.json).

It should be possible to use it directly instead of downloading from the site and then uploading it to manifoldjs

**Comment by boyofgreen** [comment]
Hey Kenchris, if the site already has one, you can just pass in the URL.  ManifoldJS will then go out and collect the manifest and images for the different packages.  Let me know if this isn't working for you, might be a bug.

**Comment by kenchris** [comment]
That doesn't work with http://www.cnet.com or http://www.cnet.com/manifest.json

**Comment by nbellocam** [comment]
After executing `manifoldjs http://www.cnet.com` we are seeing the following error message: `ERROR: Invalid manifest format.`

The tool validates the manifest found before processing it and it seems like cnet doesn't have a compliant manifest. The `icon` properties  contains a property named _size_ instead of [sizes](https://w3c.github.io/manifest/#sizes-member) (note the final _s_).

**Comment by kenchris** [comment]
I guess getting as much right info out of the invalid manifest makes sense and issuing warnings instead. That way people would know how to contact cnet.com (if it is not them packaging up their own site :))

@paulkinlan

**Comment by nbellocam** [comment]
The main issue with retriving more specific information about the invalid format of the manifest is that we are trying to detect the kind of manifest that is used as an input so, at first, we don't know what is the provided manifest format in order to validate it accordingly.

The idea behind this is to support not only W3C manifest as input but also the others manifest like the ones for Chrome and FirefoxOS. However, this is not fully implemented yet.

We could add a way to specify the kind of manifest used in order to retrieve more information or be more flexible with the manifest detection logic. I created a new item (#43) in the backlog for this. I will close this issue for now as there are no action items.

**Comment by kenchris** [comment]
I would love that the W3C spec stays the default and the promoted one. So if you want to use some other format, it should be fine to use another argument, to be more explicit.

Also, I believe the FxOS might move away from their format at some point, @marcoscaceres?

Also if people use Chrome Apps manifest there is a pretty good chance that they use chrome.* APIs which might mean that the app doesn't work out of the box and requires lots of changes, - much more than writing a W3C conformant manifest. I would guess the same applies to FxOS manifest.

**Comment by marcoscaceres** [comment]
> Also, I believe the FxOS might move away from their format at some point, @marcoscaceres?

Mozilla does not have any plans to do so right now. However, it might end up supporting both formats.

**Comment by nbellocam** [comment]
W3C spec is the core of manifoldjs and that will continue being like that. Don't worry, we are on the same track on that :smile:. All the transformations are based on the W3C spec (_from_ and _to_ W3C). 

The idea behind accepting other type of manifest formats is to fill the gap when the input manifest is different to W3C, thus helping the transition to the W3C manifest.

However, as I said before, accepting other manifest formats different from W3C is not fully implemented and scenarios like the ones you describe (using native APIs) need still to be further analyzed.
