### ISSUE TITLE
Consider renaming the still undocumented mjs_urlAccess

### ISSUE THREAD

**Issue by kenchris** [manifoldjs/ManifoldJS#31]
As most names in the W3C Manifest spec are lower case what about using something like: 

"mjs_access_whitelist"

For me it is also not clear what _urlAccess stood for... like it wasn't clear that it was a whitelisting of URLs who could access extended APIs.

**Comment by marcoscaceres** [comment]
On Thursday, April 30, 2015, Kenneth Rohde Christiansen <
notifications@github.com> wrote:

> As most names in the W3C Manifest spec are lower case what about using
> something like:
>
> "mjs_access_whitelist"
>
> For me it is also not clear what _urlAccess stood for... like it wasn't
> clear that it was a whitelisting of URLs who could access extended APIs.
>

See also:

https://w3c.github.io/manifest/#proprietary-extensions

**Comment by boyofgreen** [comment]
Your right.  This needs to be changed.   We also think this will become unnecessary if a few changes are made to the spec.  Specifically making the scope an array and adding capabilities.

**Comment by marcoscaceres** [comment]
> Your right. This needs to be changed. We also think this will become unnecessary if a few changes are made to the spec. Specifically making the scope an array and adding capabilities. 

* As the manifest spec is currently targeted at web browsers, multiple origins for scope is going to be tricky (there are a few privacy and security issues there). 
* For capabilities (again because of our focus on Web browsers), we were not able to find non-proprietary APIs that required a capabilities declaration (hence why they are missing from the spec right now). 

We are continuing to evaluate if we should consider targeting proprietary platforms with the manifest format.

**Comment by kenchris** [comment]
@boyofgreen Please file spec issues, ideas, suggestions here:

https://github.com/w3c/manifest/issues

Regarding capabilities:
* With the permission spec (non-upfront permissions) this seems like a thing that will go away
* Permissions differ a lot per platform

Due to these reasons, I think it is best that the tool will figure out what permissions to enable per platform.

AFAIU, I can use the Windows object on Windows and you will implement parts of that for other platforms using Cordova? Or Is it possible to use the Cordova APIs directly?

I think that we should create a msj_ extension here, but I need to find out exactly how all of this works in order to help you design such an extension :-)

If you support the Core Cordova APIs, we could add something like

"msj_cordova_plugin": ["battery-status", "contacts"]

where the name is taking from the plugin name itself (ie "org.apache.cordova.battery-status"). For each platform you already know which permissions each plugin requires.

If you don't support the Cordova APIs directly and just emulated Windows object, then we should find another solution. I kind of like the ability to use the core Cordova APIs though, as many hybrid apps do that already, like Untappd.

**Comment by nbellocam** [comment]
I applied the changes in [v0.2.0](https://github.com/manifoldjs/ManifoldJS/tree/v0.2.0) and moved this issue to that release since we are performing additional changes to that property due to the latest updates in the cordova plugin.

I opened a [new issue](https://github.com/manifoldjs/ManifoldJS/issues/40) to continue the discussion about capabilities in the manifest.
