### ISSUE TITLE
CLI will not generate manifest on certain sites

### ISSUE THREAD

**Issue by DaveVoyles** [manifoldjs/ManifoldJS#37]
### Method: CLI

When I point towards http://www.Babylonjs.com, it says that the file doesn’t have a manifest. This is expected, but I assumed it would try to generate a manifest on its own, as it had done for my personal website, but it does not. 

I tried again on my person site, www.DaveVoyles.com and ran into an issue. 

It runs into an issue when trying to find the icons. I noticed that on the web based generator, I don’t have any icons for my links, but it tries to force them with an empty box next to the links in the header.  

#### Image 1: http://www.davevoyles.com/wp-content/uploads/2015/05/Manifold-Error-DaveVoylesdotcom.jpeg

I can run the Web Based Manifest Generator, and it all works fine. Here is an image of my website being running inside of the WIn Phone emulator running Cordova. I can see that isse with the icons here.

**Comment by nbellocam** [comment]
Thanks for reporting this.

Regarding the issue with the icons. It should be already fixed in [v0.1.3](https://github.com/manifoldjs/ManifoldJS/tree/v0.1.3) with this commit: https://github.com/manifoldjs/ManifoldJS/commit/786ff5bb538f67829d0c7d97dccfbbd3c3846c87

With this update it seems that the tool is generating the apps for both sites. I will close this issue for now, let us know if you continue seeing these issues. (If you want to test with v0.1.3 uninstall manifoldjs using `npm uninstall -g manifoldjs` and install it again using `npm install -g manifoldjs/manifoldjs#v0.1.3`)
