### ISSUE TITLE
Does manifold.js require the project utilize Cordova?

### ISSUE THREAD

**Issue by gavinengel** [manifoldjs/ManifoldJS#47]
So, I'm looking to avoid Cordova/Webview-based solutions from a future 'universal app' build process.  Does manifold.js require Cordova on projects?  Or is it like NativeScript?

Also, do you have Gitter room for casual questions like mine?

**Comment by boyofgreen** [comment]
Hi Gavin,
  ManifoldJS builds [hosted web apps](http://www.thishereweb.com/hosted-web-apps-explained/) from the W3C manifest.  We use Cordova and webviews when the platforms does't support native hosted apps.  So that would be for iOS, Android and Windows 8.1.  Windows 10, chrome and FFOS are all straight natively supported hosted apps.
  The hosted apps are still a web runtime environment, but generally have access to more APIs, and of course can be submitted to the stores.  We don't have a Gitter room at this point, but I'll look into it, thanks for the suggestion!  If ManifoldJS works for you, we hope you enjoy it, if not, good luck with whatever you choose!

**Comment by gavinengel** [comment]
Oh interesting.  Thank for you this.

**Comment by gavinengel** [comment]
I left a comment on your blog... I hope it isn't a redundant question.  I guess I was looking for more of your thoughts on NativeScript and React Native.
